name: fleetease_android_app
description: "FleetEase Android Flutter app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
