name: Flutter CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run flutter analyze
        run: bash run_flutter_ci_strict.sh analyze

      - name: Run flutter test
        run: bash run_flutter_ci_strict.sh test
