name: Flutter CI

on:
  push:
  pull_request:

jobs:
  analyze_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Analyze
        run: |
          bash ci_entry.sh pub get
          bash ci_entry.sh analyze

      - name: Test
        run: |
          CI=true bash ci_entry.sh test -r expanded
