name: fleet_management_workspace
description: "Workspace marker for FleetEase projects"
publish_to: "none"
environment:
  sdk: ">=3.7.0 <4.0.0"
# This is not a Flutter app; refer to fleetease_android_app for the actual project.
